// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOEfJvfTCYVgjQna__M0xrjJIAsU9qVbQ',
    appId: '1:396832436896:web:bc488081b5cc9c246fcfc5',
    messagingSenderId: '396832436896',
    projectId: 'organaizo',
    authDomain: 'organaizo.firebaseapp.com',
    storageBucket: 'organaizo.appspot.com',
    measurementId: 'G-Y9EBRD5XWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDqRzs-x11Oi80dQ1utJ51MHekAvNBzN8',
    appId: '1:396832436896:android:be97e2cf4f9c15f36fcfc5',
    messagingSenderId: '396832436896',
    projectId: 'organaizo',
    storageBucket: 'organaizo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQmNGmxk_UKpKdAz7JBngt7qGNelup0fI',
    appId: '1:396832436896:ios:5a44262cd44094e76fcfc5',
    messagingSenderId: '396832436896',
    projectId: 'organaizo',
    storageBucket: 'organaizo.appspot.com',
    iosBundleId: 'com.example.mobileAppOrganaizo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQmNGmxk_UKpKdAz7JBngt7qGNelup0fI',
    appId: '1:396832436896:ios:b6ee7f4356daae3d6fcfc5',
    messagingSenderId: '396832436896',
    projectId: 'organaizo',
    storageBucket: 'organaizo.appspot.com',
    iosBundleId: 'com.example.mobileAppOrganaizo.RunnerTests',
  );
}
